data_root: "./data"
image_size: 256
batch_size: 16
pretrain_batch_size: 160
num_workers: 8
seed: 42
device: "cuda"
amp: true

split:
  val_ratio: 0.20
  test_ratio: 0.10

task:
  run_seg: true
  run_cls: true
  run_pretrain: true
  run_pretrained_encoder_to_seg: true

optim:
  lr: 1e-3
  weight_decay: 1e-4

epochs:
  seg: 150
  cls: 150
  pretrain: 100
  seg_ft: 50
  freeze_encoder_epochs: 5

model:
  base_channels: 32
  depth: 4

pretrain:
  # 自监督（SimCLR风格）的一些设置
  proj_dim: 128
  temperature: 0.2
